### ISSUE TITLE
關於課表列印

### ISSUE THREAD

**Issue by pudding0803** [zetaraku/NCU-Course-Finder-v6#1]
課表列印不會印到晚上的部分

**Comment by zetaraku** [comment]
感謝回報！

原本想說沒辦法把課表完整的印成一頁，就把晚上的課表藏起來了 :P
現在課表已經可以列印到晚上的部分了 ~~，但這部分 code 還有點醜~~


另外也修復了幾個問題，現在在列印模式中：

- 課程名稱會以適當的字型大小顯示
- 課程名稱連結會正常以深黑色顯示
- 午休及晚上的時段將不會帶有底色

如果還有其他問題還麻煩回報，謝謝！:)
